package gui;
import ClassTemplates.Book;
import ClassTemplates.Borrow;
import ClassTemplates.Student;
import java.util.HashMap;
import java.util.List;
import utiler.DataProcessor;


/**
 *
 * @author arfcd
 */
public class MainGui extends javax.swing.JFrame {
    
    private DataProcessor dataProc;
    /**
     * Creates new form MainGui
     */
    public MainGui() {
        initComponents();
        
    }
    
    public void setDataBase(List<Student> students, List<Borrow> borrows, List<Book> books, int daysPerBorrow, double dailyFee){
        this.dataProc = new DataProcessor(students, borrows, books, daysPerBorrow, dailyFee);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        container = new javax.swing.JTabbedPane();
        overview = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        overviewContainer = new javax.swing.JScrollPane();
        overviewTable = new javax.swing.JTable();
        brOverview = new javax.swing.JLabel();
        brActive = new javax.swing.JLabel();
        brActiveNum = new javax.swing.JLabel();
        brExprNum = new javax.swing.JLabel();
        brExpr = new javax.swing.JLabel();
        boBorrwdNum = new javax.swing.JLabel();
        boBorrwd = new javax.swing.JLabel();
        boAvailNum = new javax.swing.JLabel();
        boAvail = new javax.swing.JLabel();
        bookOverview = new javax.swing.JLabel();
        sOverview = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        regStudentsNum = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        reloadBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        borrow = new javax.swing.JPanel();
        returnedBorrows = new javax.swing.JRadioButton();
        activeBorrows = new javax.swing.JRadioButton();
        expiringBorrow = new javax.swing.JRadioButton();
        expiredBorrow = new javax.swing.JRadioButton();
        overviewContainer1 = new javax.swing.JScrollPane();
        borrowsTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        bookComboBox = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        stuComboBox = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        allBorrows = new javax.swing.JRadioButton();
        detailsPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        stuCode = new javax.swing.JLabel();
        stuName = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        bookCode = new javax.swing.JLabel();
        bookName = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        startBorrowDate = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        endBorrowDate = new javax.swing.JLabel();
        borrowResult = new javax.swing.JLabel();
        bookAuthor = new javax.swing.JLabel();
        book = new javax.swing.JPanel();
        bookContainer = new javax.swing.JScrollPane();
        booksTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        student = new javax.swing.JPanel();
        Conta = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library");
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(800, 700));
        setMinimumSize(new java.awt.Dimension(800, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        container.setMaximumSize(new java.awt.Dimension(800, 700));
        container.setMinimumSize(new java.awt.Dimension(800, 700));
        container.setPreferredSize(new java.awt.Dimension(800, 700));

        overview.setMaximumSize(new java.awt.Dimension(800, 700));
        overview.setMinimumSize(new java.awt.Dimension(800, 700));
        overview.setPreferredSize(new java.awt.Dimension(800, 700));

        title.setText("General overview:");

        overviewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        overviewTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                overviewTableMouseClicked(evt);
            }
        });
        overviewContainer.setViewportView(overviewTable);

        brOverview.setText("Borrows");

        brActive.setText("Active:");

        brActiveNum.setText("jLabel3");

        brExprNum.setText("jLabel3");

        brExpr.setText("Expired:");

        boBorrwdNum.setText("jLabel3");

        boBorrwd.setText("Borrowed:");

        boAvailNum.setText("jLabel3");

        boAvail.setText("Avaliable:");

        bookOverview.setText("Books");

        sOverview.setText("Students");

        jLabel12.setText("Reg. Students:");

        regStudentsNum.setText("jLabel3");

        jLabel1.setText("Expires Today");

        jButton1.setText("Return");
        jButton1.setMaximumSize(new java.awt.Dimension(85, 25));
        jButton1.setMinimumSize(new java.awt.Dimension(85, 25));
        jButton1.setPreferredSize(new java.awt.Dimension(85, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("New");
        jButton2.setMaximumSize(new java.awt.Dimension(85, 25));
        jButton2.setMinimumSize(new java.awt.Dimension(85, 25));
        jButton2.setPreferredSize(new java.awt.Dimension(85, 25));

        reloadBtn.setText("Reload");
        reloadBtn.setMaximumSize(new java.awt.Dimension(85, 25));
        reloadBtn.setMinimumSize(new java.awt.Dimension(85, 25));
        reloadBtn.setPreferredSize(new java.awt.Dimension(85, 25));
        reloadBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reloadBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout overviewLayout = new javax.swing.GroupLayout(overview);
        overview.setLayout(overviewLayout);
        overviewLayout.setHorizontalGroup(
            overviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overviewLayout.createSequentialGroup()
                .addGroup(overviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(overviewLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(overviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(title)
                            .addGroup(overviewLayout.createSequentialGroup()
                                .addComponent(reloadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(overviewContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(overviewLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(overviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(overviewLayout.createSequentialGroup()
                                .addGroup(overviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(brActive)
                                    .addComponent(brOverview))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(brActiveNum))
                            .addGroup(overviewLayout.createSequentialGroup()
                                .addComponent(brExpr)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(brExprNum)))
                        .addGap(112, 112, 112)
                        .addGroup(overviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(overviewLayout.createSequentialGroup()
                                .addComponent(boAvail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boAvailNum))
                            .addGroup(overviewLayout.createSequentialGroup()
                                .addGroup(overviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(boBorrwd)
                                    .addComponent(bookOverview))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boBorrwdNum)))
                        .addGap(112, 112, 112)
                        .addGroup(overviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(sOverview))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(regStudentsNum)))
                .addGap(31, 31, 31))
        );
        overviewLayout.setVerticalGroup(
            overviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overviewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(overviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(overviewLayout.createSequentialGroup()
                        .addComponent(brOverview)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(overviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(brActive)
                            .addComponent(brActiveNum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(overviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(brExpr)
                            .addComponent(brExprNum)))
                    .addGroup(overviewLayout.createSequentialGroup()
                        .addGroup(overviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(overviewLayout.createSequentialGroup()
                                .addComponent(bookOverview)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(overviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(boBorrwd)
                                    .addComponent(boBorrwdNum)))
                            .addGroup(overviewLayout.createSequentialGroup()
                                .addComponent(sOverview)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(overviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(regStudentsNum))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(overviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boAvail)
                            .addComponent(boAvailNum))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(overviewContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(overviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reloadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 78, Short.MAX_VALUE))
        );

        container.addTab("Overview", overview);

        buttonGroup1.add(returnedBorrows);
        returnedBorrows.setText("Returned");
        returnedBorrows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnedBorrowsActionPerformed(evt);
            }
        });

        buttonGroup1.add(activeBorrows);
        activeBorrows.setText("Active");
        activeBorrows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activeBorrowsActionPerformed(evt);
            }
        });

        buttonGroup1.add(expiringBorrow);
        expiringBorrow.setText("Expires today");
        expiringBorrow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                expiringBorrowMouseClicked(evt);
            }
        });

        buttonGroup1.add(expiredBorrow);
        expiredBorrow.setText("Expired");
        expiredBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expiredBorrowActionPerformed(evt);
            }
        });

        borrowsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        borrowsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrowsTableMouseClicked(evt);
            }
        });
        overviewContainer1.setViewportView(borrowsTable);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel13.setText("New Borrow");

        bookComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel14.setText("Book");

        jLabel15.setText("Student");

        stuComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton4.setText("Save");
        jButton4.setMaximumSize(new java.awt.Dimension(85, 25));
        jButton4.setMinimumSize(new java.awt.Dimension(85, 25));
        jButton4.setPreferredSize(new java.awt.Dimension(85, 25));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel16.setText("Avaliable:");

        jLabel17.setText("% rate:");

        jLabel18.setText("000");

        jLabel19.setText("000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(167, 167, 167))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19))
                            .addComponent(stuComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stuComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        buttonGroup1.add(allBorrows);
        allBorrows.setSelected(true);
        allBorrows.setText("All");
        allBorrows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allBorrowsActionPerformed(evt);
            }
        });

        detailsPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel8.setText("Details:");

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel9.setText("Student:");

        stuCode.setText("code :");

        stuName.setText("Names Lastnames");

        jLabel20.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel20.setText("Book:");

        bookCode.setText("code :");

        bookName.setText("Book name");

        jLabel23.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel23.setText("Borrow:");

        jLabel24.setText("from:");

        startBorrowDate.setText("2024-05-05");

        jLabel26.setText("to:");

        endBorrowDate.setText("2024-06-06");

        borrowResult.setText("4 days - Q 45.6");

        bookAuthor.setText("Book Author");

        javax.swing.GroupLayout detailsPanelLayout = new javax.swing.GroupLayout(detailsPanel);
        detailsPanel.setLayout(detailsPanelLayout);
        detailsPanelLayout.setHorizontalGroup(
            detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsPanelLayout.createSequentialGroup()
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailsPanelLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel8))
                    .addGroup(detailsPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel20)
                                .addComponent(jLabel23))
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stuName)
                            .addComponent(bookName)
                            .addComponent(stuCode)
                            .addComponent(bookCode)
                            .addComponent(borrowResult)
                            .addGroup(detailsPanelLayout.createSequentialGroup()
                                .addComponent(startBorrowDate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(endBorrowDate))
                            .addComponent(bookAuthor))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        detailsPanelLayout.setVerticalGroup(
            detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(stuCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stuName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(bookCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookAuthor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(borrowResult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startBorrowDate)
                    .addComponent(jLabel26)
                    .addComponent(endBorrowDate)
                    .addComponent(jLabel24))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout borrowLayout = new javax.swing.GroupLayout(borrow);
        borrow.setLayout(borrowLayout);
        borrowLayout.setHorizontalGroup(
            borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrowLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(overviewContainer1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(borrowLayout.createSequentialGroup()
                        .addComponent(allBorrows)
                        .addGap(74, 74, 74)
                        .addComponent(returnedBorrows)
                        .addGap(69, 69, 69)
                        .addComponent(activeBorrows)
                        .addGap(79, 79, 79)
                        .addComponent(expiringBorrow)
                        .addGap(70, 70, 70)
                        .addComponent(expiredBorrow))
                    .addGroup(borrowLayout.createSequentialGroup()
                        .addComponent(detailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        borrowLayout.setVerticalGroup(
            borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrowLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnedBorrows)
                    .addComponent(activeBorrows)
                    .addComponent(expiringBorrow)
                    .addComponent(expiredBorrow)
                    .addComponent(allBorrows))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(overviewContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(detailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        container.addTab("Borrows", borrow);

        booksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        bookContainer.setViewportView(booksTable);

        jLabel2.setText("Avaliable:");

        jLabel3.setText("Total:");

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        jLabel5.setText("jLabel5");

        jLabel4.setText("Borrowed:");

        javax.swing.GroupLayout bookLayout = new javax.swing.GroupLayout(book);
        book.setLayout(bookLayout);
        bookLayout.setHorizontalGroup(
            bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(159, 159, 159)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(bookLayout.createSequentialGroup()
                        .addComponent(bookContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        bookLayout.setVerticalGroup(
            bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(bookContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addContainerGap(232, Short.MAX_VALUE))
        );

        container.addTab("Books", book);

        javax.swing.GroupLayout studentLayout = new javax.swing.GroupLayout(student);
        student.setLayout(studentLayout);
        studentLayout.setHorizontalGroup(
            studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        studentLayout.setVerticalGroup(
            studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 669, Short.MAX_VALUE)
        );

        container.addTab("Students", student);

        javax.swing.GroupLayout ContaLayout = new javax.swing.GroupLayout(Conta);
        Conta.setLayout(ContaLayout);
        ContaLayout.setHorizontalGroup(
            ContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        ContaLayout.setVerticalGroup(
            ContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 669, Short.MAX_VALUE)
        );

        container.addTab("Conta", Conta);

        getContentPane().add(container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnedBorrowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnedBorrowsActionPerformed
        this.loadBorrows("r");
    }//GEN-LAST:event_returnedBorrowsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void reloadBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reloadBtnMouseClicked
        this.dataProc.updateStatistics();
        this.loadOverview();
        System.out.println("reloaded");
    }//GEN-LAST:event_reloadBtnMouseClicked

    private void activeBorrowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activeBorrowsActionPerformed
        this.loadBorrows("ac");
    }//GEN-LAST:event_activeBorrowsActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void allBorrowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allBorrowsActionPerformed
        this.loadBorrows("all");
    }//GEN-LAST:event_allBorrowsActionPerformed

    private void expiredBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expiredBorrowActionPerformed
        this.loadBorrows("e");
    }//GEN-LAST:event_expiredBorrowActionPerformed

    private void expiringBorrowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expiringBorrowMouseClicked
        this.loadBorrows("et");
    }//GEN-LAST:event_expiringBorrowMouseClicked

    private void overviewTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_overviewTableMouseClicked
        System.out.println(this.overviewTable.getModel().getValueAt(this.overviewTable.getSelectedRow(), 0));
    }//GEN-LAST:event_overviewTableMouseClicked

    private void borrowsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrowsTableMouseClicked
        List<String[]> bDetails = this.dataProc.getBorrowDetails(
                this.borrowsTable.getModel().getValueAt(
                        this.borrowsTable.getSelectedRow(), 0)
                        .toString());
        this.stuCode.setText(bDetails.getFirst()[0]);
        this.stuName.setText(bDetails.getFirst()[1]);
        this.bookCode.setText(bDetails.get(1)[0]);
        this.bookName.setText(bDetails.get(1)[1]);
        this.bookAuthor.setText(bDetails.get(1)[2]);
        this.startBorrowDate.setText(bDetails.get(2)[0]);
        this.endBorrowDate.setText(bDetails.get(2)[1]);
        this.borrowResult.setText(bDetails.get(2)[2] +" days -> Q. "+ bDetails.get(2)[3]);
    }//GEN-LAST:event_borrowsTableMouseClicked

    public void loadNewBorrowCombobox(){
        this.stuComboBox.addItem("string item");
    }
    
    public void loadOverview(){
        this.overviewTable.setModel(this.dataProc.overviewTab());
        this.overviewTable.getColumn("Code").setPreferredWidth(90);
        this.overviewTable.getColumn("Code").setMaxWidth(90);
        /*this.overviewTable.getColumn("Book ISBN").setPreferredWidth(120);
        this.overviewTable.getColumn("Book ISBN").setMaxWidth(120);*/
        this.overviewTable.getColumn("To Pay").setPreferredWidth(60);
        this.overviewTable.getColumn("To Pay").setMaxWidth(60);
        /*this.overviewTable.getColumn("Student").setPreferredWidth(90);
        this.overviewTable.getColumn("Student").setMaxWidth(90);*/
        this.overviewTable.getColumn("Days").setPreferredWidth(55);
        this.overviewTable.getColumn("Days").setMaxWidth(55);
        
        HashMap map = this.dataProc.getStatistics();
        this.brActiveNum.setText(String.valueOf(map.get("borrowedBooks")));
        this.boBorrwdNum.setText(String.valueOf(map.get("borrowedBooks")));
        this.regStudentsNum.setText(String.valueOf(map.get("students")));
        this.brExprNum.setText(String.valueOf(map.get("expiredBorr")));
        this.boAvailNum.setText(String.valueOf((Integer)map.get("totBook")-(Integer)map.get("borrowedBooks")));
    }
    
    public void loadBorrows(String filter){
        this.borrowsTable.setModel(this.dataProc.borrowsTab(filter));
        this.borrowsTable.getColumn("Code").setPreferredWidth(90);
        this.borrowsTable.getColumn("Code").setMaxWidth(90);
        
    }
    
    public void loadBooks(){
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Conta;
    private javax.swing.JRadioButton activeBorrows;
    private javax.swing.JRadioButton allBorrows;
    private javax.swing.JLabel boAvail;
    private javax.swing.JLabel boAvailNum;
    private javax.swing.JLabel boBorrwd;
    private javax.swing.JLabel boBorrwdNum;
    private javax.swing.JPanel book;
    private javax.swing.JLabel bookAuthor;
    private javax.swing.JLabel bookCode;
    private javax.swing.JComboBox<String> bookComboBox;
    private javax.swing.JScrollPane bookContainer;
    private javax.swing.JLabel bookName;
    private javax.swing.JLabel bookOverview;
    private javax.swing.JTable booksTable;
    private javax.swing.JPanel borrow;
    private javax.swing.JLabel borrowResult;
    private javax.swing.JTable borrowsTable;
    private javax.swing.JLabel brActive;
    private javax.swing.JLabel brActiveNum;
    private javax.swing.JLabel brExpr;
    private javax.swing.JLabel brExprNum;
    private javax.swing.JLabel brOverview;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTabbedPane container;
    private javax.swing.JPanel detailsPanel;
    private javax.swing.JLabel endBorrowDate;
    private javax.swing.JRadioButton expiredBorrow;
    private javax.swing.JRadioButton expiringBorrow;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel overview;
    private javax.swing.JScrollPane overviewContainer;
    private javax.swing.JScrollPane overviewContainer1;
    private javax.swing.JTable overviewTable;
    private javax.swing.JLabel regStudentsNum;
    private javax.swing.JButton reloadBtn;
    private javax.swing.JRadioButton returnedBorrows;
    private javax.swing.JLabel sOverview;
    private javax.swing.JLabel startBorrowDate;
    private javax.swing.JLabel stuCode;
    private javax.swing.JComboBox<String> stuComboBox;
    private javax.swing.JLabel stuName;
    private javax.swing.JPanel student;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
