package Gui;

import Models.Book;
import Models.Borrow;
import Models.Student;
import java.util.HashMap;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import Utils.DataProcessor;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author arfcd
 */
public class MainGui extends javax.swing.JFrame {

    private DataProcessor dataProc;
    private int daysPerBorrow = 0;
    private double dailyFee = 0.0;

    /**
     * Creates new form MainGui
     */
    public MainGui() {
        initComponents();

    }

    public void setDataBase(List<Student> students, List<Borrow> borrows, List<Book> books, int daysPerBorrow, double dailyFee) {
        this.dataProc = new DataProcessor(students, borrows, books, daysPerBorrow, dailyFee);
        this.dailyFee = dailyFee;
        this.daysPerBorrow = daysPerBorrow;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        container = new javax.swing.JTabbedPane();
        overview = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        overviewContainer = new javax.swing.JScrollPane();
        overviewTable = new javax.swing.JTable();
        brOverview = new javax.swing.JLabel();
        brActive = new javax.swing.JLabel();
        brActiveNum = new javax.swing.JLabel();
        brExprNum = new javax.swing.JLabel();
        brExpr = new javax.swing.JLabel();
        boBorrwdNum = new javax.swing.JLabel();
        boBorrwd = new javax.swing.JLabel();
        boAvailNum = new javax.swing.JLabel();
        boAvail = new javax.swing.JLabel();
        bookOverview = new javax.swing.JLabel();
        sOverview = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        regStudentsNum = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        returnBookBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        reloadBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        borrow = new javax.swing.JPanel();
        returnedBorrows = new javax.swing.JRadioButton();
        activeBorrows = new javax.swing.JRadioButton();
        expiringBorrow = new javax.swing.JRadioButton();
        expiredBorrow = new javax.swing.JRadioButton();
        overviewContainer1 = new javax.swing.JScrollPane();
        borrowsTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        bookComboBox = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        stuComboBox = new javax.swing.JComboBox<>();
        saveNewBorrow = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        duration = new javax.swing.JLabel();
        dailyCost = new javax.swing.JLabel();
        allBorrows = new javax.swing.JRadioButton();
        detailsPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        stuCode = new javax.swing.JLabel();
        stuName = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        bookCode = new javax.swing.JLabel();
        bookName = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        startBorrowDate = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        endBorrowDate = new javax.swing.JLabel();
        borrowResult = new javax.swing.JLabel();
        bookAuthor = new javax.swing.JLabel();
        book = new javax.swing.JPanel();
        bookContainer = new javax.swing.JScrollPane();
        booksTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        newBookCode = new javax.swing.JTextField();
        newBookTitle = new javax.swing.JTextField();
        newBookAuthor = new javax.swing.JTextField();
        newBookEditorial = new javax.swing.JTextField();
        newBookEdition = new javax.swing.JTextField();
        saveNewBook = new javax.swing.JButton();
        newBookStock = new javax.swing.JTextField();
        findCriteria = new javax.swing.JTextField();
        findBooksBtn = new javax.swing.JButton();
        bookTitleChooser = new javax.swing.JRadioButton();
        bookAuthorChooser = new javax.swing.JRadioButton();
        bookEditorialChooser = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        totalReg = new javax.swing.JLabel();
        currOutOf = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        student = new javax.swing.JPanel();
        stuContainer = new javax.swing.JScrollPane();
        stuTable = new javax.swing.JTable();
        inactiveStudents = new javax.swing.JRadioButton();
        activeStudents = new javax.swing.JRadioButton();
        allStudents = new javax.swing.JRadioButton();
        fltrStuByName = new javax.swing.JRadioButton();
        fltrStuByCode = new javax.swing.JRadioButton();
        fltrStuByDeg = new javax.swing.JRadioButton();
        stuFilterCriteria = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        newStuName = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        newStuDeg = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        newStuIdCard = new javax.swing.JTextField();
        saveNewStu = new javax.swing.JButton();
        reloadStuCode = new javax.swing.JButton();
        newStuDob = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        stuCodeLabl = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        stuNamelabl = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        stuDobLabl = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        stuDegLabl = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        activeStuLoans = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        allStuLoans = new javax.swing.JLabel();
        Conta = new javax.swing.JPanel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(800, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        container.setMaximumSize(new java.awt.Dimension(800, 700));
        container.setMinimumSize(new java.awt.Dimension(800, 700));
        container.setPreferredSize(new java.awt.Dimension(800, 700));

        overview.setMaximumSize(new java.awt.Dimension(800, 700));
        overview.setMinimumSize(new java.awt.Dimension(800, 700));
        overview.setPreferredSize(new java.awt.Dimension(800, 700));

        title.setText("General overview:");

        overviewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        overviewTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                overviewTableMouseClicked(evt);
            }
        });
        overviewContainer.setViewportView(overviewTable);

        brOverview.setText("Loans");

        brActive.setText("Active:");

        brActiveNum.setText("jLabel3");

        brExprNum.setText("jLabel3");

        brExpr.setText("Expired:");

        boBorrwdNum.setText("jLabel3");

        boBorrwd.setText("Borrowed:");

        boAvailNum.setText("jLabel3");

        boAvail.setText("Avaliable:");

        bookOverview.setText("Books");

        sOverview.setText("Students");

        jLabel12.setText("Reg. Students:");

        regStudentsNum.setText("jLabel3");

        jLabel1.setText("Expires Today");

        returnBookBtn.setText("Return");
        returnBookBtn.setMaximumSize(new java.awt.Dimension(85, 25));
        returnBookBtn.setMinimumSize(new java.awt.Dimension(85, 25));
        returnBookBtn.setPreferredSize(new java.awt.Dimension(85, 25));
        returnBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBookBtnActionPerformed(evt);
            }
        });

        jButton2.setText("New");
        jButton2.setMaximumSize(new java.awt.Dimension(85, 25));
        jButton2.setMinimumSize(new java.awt.Dimension(85, 25));
        jButton2.setPreferredSize(new java.awt.Dimension(85, 25));

        reloadBtn.setText("Reload");
        reloadBtn.setMaximumSize(new java.awt.Dimension(85, 25));
        reloadBtn.setMinimumSize(new java.awt.Dimension(85, 25));
        reloadBtn.setPreferredSize(new java.awt.Dimension(85, 25));
        reloadBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reloadBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout overviewLayout = new javax.swing.GroupLayout(overview);
        overview.setLayout(overviewLayout);
        overviewLayout.setHorizontalGroup(
            overviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overviewLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(overviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(overviewLayout.createSequentialGroup()
                        .addGroup(overviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(brOverview)
                            .addComponent(brActive)
                            .addComponent(brExpr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(overviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(brExprNum)
                            .addComponent(brActiveNum))
                        .addGap(164, 164, 164)
                        .addGroup(overviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(overviewLayout.createSequentialGroup()
                                .addComponent(boAvail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boAvailNum))
                            .addGroup(overviewLayout.createSequentialGroup()
                                .addGroup(overviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(boBorrwd)
                                    .addComponent(bookOverview))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boBorrwdNum)))
                        .addGap(129, 129, 129)
                        .addGroup(overviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(sOverview))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(regStudentsNum))
                    .addGroup(overviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(title)
                        .addGroup(overviewLayout.createSequentialGroup()
                            .addComponent(reloadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(returnBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(overviewContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                        .addComponent(jSeparator1)))
                .addGap(31, 31, 31))
        );
        overviewLayout.setVerticalGroup(
            overviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overviewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(overviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(overviewLayout.createSequentialGroup()
                        .addGroup(overviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(brActive)
                            .addComponent(brActiveNum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(overviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(brExpr)
                            .addComponent(brExprNum)))
                    .addGroup(overviewLayout.createSequentialGroup()
                        .addComponent(sOverview)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(overviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(regStudentsNum))
                        .addGap(25, 25, 25))
                    .addGroup(overviewLayout.createSequentialGroup()
                        .addGroup(overviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bookOverview)
                            .addComponent(brOverview))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(overviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boBorrwd)
                            .addComponent(boBorrwdNum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(overviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boAvail)
                            .addComponent(boAvailNum))))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(overviewContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(overviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reloadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 90, Short.MAX_VALUE))
        );

        container.addTab("Overview", overview);

        buttonGroup1.add(returnedBorrows);
        returnedBorrows.setText("Returned");
        returnedBorrows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnedBorrowsActionPerformed(evt);
            }
        });

        buttonGroup1.add(activeBorrows);
        activeBorrows.setText("Active");
        activeBorrows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activeBorrowsActionPerformed(evt);
            }
        });

        buttonGroup1.add(expiringBorrow);
        expiringBorrow.setText("Expires today");
        expiringBorrow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                expiringBorrowMouseClicked(evt);
            }
        });

        buttonGroup1.add(expiredBorrow);
        expiredBorrow.setText("Expired");
        expiredBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expiredBorrowActionPerformed(evt);
            }
        });

        borrowsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        borrowsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrowsTableMouseClicked(evt);
            }
        });
        overviewContainer1.setViewportView(borrowsTable);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel13.setText("New Loan");

        bookComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel14.setText("Book");

        jLabel15.setText("Student");

        stuComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        saveNewBorrow.setText("Save");
        saveNewBorrow.setMaximumSize(new java.awt.Dimension(85, 25));
        saveNewBorrow.setMinimumSize(new java.awt.Dimension(85, 25));
        saveNewBorrow.setPreferredSize(new java.awt.Dimension(85, 25));
        saveNewBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveNewBorrowActionPerformed(evt);
            }
        });

        jLabel16.setText("Duration:");

        jLabel17.setText("% rate:");

        duration.setText("000");

        dailyCost.setText("000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(saveNewBorrow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(duration)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dailyCost))
                                    .addComponent(stuComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bookComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel13)))
                .addGap(0, 46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stuComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(duration)
                    .addComponent(jLabel17)
                    .addComponent(dailyCost))
                .addGap(18, 18, 18)
                .addComponent(saveNewBorrow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        buttonGroup1.add(allBorrows);
        allBorrows.setSelected(true);
        allBorrows.setText("All");
        allBorrows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allBorrowsActionPerformed(evt);
            }
        });

        detailsPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel8.setText("Details:");

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel9.setText("Student:");

        stuCode.setText("code");

        stuName.setText("student names");

        jLabel20.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel20.setText("Book:");

        bookCode.setText("code");

        bookName.setText("Book name");

        jLabel23.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel23.setText("Loan:");

        jLabel24.setText("from:");

        startBorrowDate.setText("2024-01-01");

        jLabel26.setText("to:");

        endBorrowDate.setText("2024-01-01");

        borrowResult.setText("0 days - Q 00.0");

        bookAuthor.setText("Book Author");

        javax.swing.GroupLayout detailsPanelLayout = new javax.swing.GroupLayout(detailsPanel);
        detailsPanel.setLayout(detailsPanelLayout);
        detailsPanelLayout.setHorizontalGroup(
            detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsPanelLayout.createSequentialGroup()
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailsPanelLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel8))
                    .addGroup(detailsPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel20)
                                .addComponent(jLabel23))
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stuName)
                            .addComponent(bookName)
                            .addComponent(stuCode)
                            .addComponent(bookCode)
                            .addComponent(borrowResult)
                            .addGroup(detailsPanelLayout.createSequentialGroup()
                                .addComponent(startBorrowDate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(endBorrowDate))
                            .addComponent(bookAuthor))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        detailsPanelLayout.setVerticalGroup(
            detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(stuCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stuName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(bookCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookAuthor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(borrowResult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startBorrowDate)
                    .addComponent(jLabel26)
                    .addComponent(endBorrowDate)
                    .addComponent(jLabel24))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout borrowLayout = new javax.swing.GroupLayout(borrow);
        borrow.setLayout(borrowLayout);
        borrowLayout.setHorizontalGroup(
            borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrowLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(overviewContainer1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(borrowLayout.createSequentialGroup()
                        .addComponent(allBorrows)
                        .addGap(74, 74, 74)
                        .addComponent(returnedBorrows)
                        .addGap(69, 69, 69)
                        .addComponent(activeBorrows)
                        .addGap(79, 79, 79)
                        .addComponent(expiringBorrow)
                        .addGap(70, 70, 70)
                        .addComponent(expiredBorrow))
                    .addGroup(borrowLayout.createSequentialGroup()
                        .addComponent(detailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        borrowLayout.setVerticalGroup(
            borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrowLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnedBorrows)
                    .addComponent(activeBorrows)
                    .addComponent(expiringBorrow)
                    .addComponent(expiredBorrow)
                    .addComponent(allBorrows))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(overviewContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(detailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        container.addTab("Loans", borrow);

        booksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        bookContainer.setViewportView(booksTable);

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel10.setText("New Book");

        jLabel5.setText("Code: ");

        jLabel6.setText("Title:");

        jLabel7.setText("Author:");

        jLabel11.setText("Editorial:");

        jLabel18.setText("Edition:");

        jLabel19.setText("Stock:");

        saveNewBook.setText("save");
        saveNewBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveNewBookMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newBookCode)
                            .addComponent(newBookTitle)
                            .addComponent(newBookEdition, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newBookEditorial, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(newBookAuthor)
                            .addComponent(newBookStock)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(saveNewBook, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(newBookCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(newBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(newBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(newBookEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(newBookEdition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newBookStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveNewBook)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        findCriteria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                findCriteriaKeyReleased(evt);
            }
        });

        findBooksBtn.setText("Find");
        findBooksBtn.setMaximumSize(new java.awt.Dimension(85, 25));
        findBooksBtn.setMinimumSize(new java.awt.Dimension(85, 25));
        findBooksBtn.setPreferredSize(new java.awt.Dimension(85, 25));
        findBooksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findBooksBtnActionPerformed(evt);
            }
        });

        buttonGroup2.add(bookTitleChooser);
        bookTitleChooser.setSelected(true);
        bookTitleChooser.setText("Title");
        bookTitleChooser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookTitleChooserMouseClicked(evt);
            }
        });

        buttonGroup2.add(bookAuthorChooser);
        bookAuthorChooser.setText("Author");
        bookAuthorChooser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookAuthorChooserMouseClicked(evt);
            }
        });

        buttonGroup2.add(bookEditorialChooser);
        bookEditorialChooser.setText("Editorial");
        bookEditorialChooser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookEditorialChooserMouseClicked(evt);
            }
        });

        jLabel2.setText("Total registred books: ");

        totalReg.setText("00000");

        currOutOf.setText("00000");

        jLabel21.setText("Currently ouf of stock:");

        javax.swing.GroupLayout bookLayout = new javax.swing.GroupLayout(book);
        book.setLayout(bookLayout);
        bookLayout.setHorizontalGroup(
            bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalReg)
                        .addGap(159, 159, 159)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(currOutOf))
                    .addGroup(bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(bookLayout.createSequentialGroup()
                            .addGap(174, 174, 174)
                            .addComponent(bookTitleChooser)
                            .addGap(18, 18, 18)
                            .addComponent(bookAuthorChooser)
                            .addGap(18, 18, 18)
                            .addComponent(bookEditorialChooser)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(findCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(findBooksBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(bookContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        bookLayout.setVerticalGroup(
            bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findBooksBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookTitleChooser)
                    .addComponent(bookAuthorChooser)
                    .addComponent(bookEditorialChooser))
                .addGap(18, 18, 18)
                .addComponent(bookContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(currOutOf)
                        .addComponent(jLabel21))
                    .addGroup(bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(totalReg)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        container.addTab("Books", book);

        stuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        stuTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stuTableMouseClicked(evt);
            }
        });
        stuContainer.setViewportView(stuTable);

        buttonGroup3.add(inactiveStudents);
        inactiveStudents.setText("Inactive");
        inactiveStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inactiveStudentsMouseClicked(evt);
            }
        });

        buttonGroup3.add(activeStudents);
        activeStudents.setText("Active");
        activeStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                activeStudentsMouseClicked(evt);
            }
        });

        buttonGroup3.add(allStudents);
        allStudents.setSelected(true);
        allStudents.setText("All");
        allStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allStudentsMouseClicked(evt);
            }
        });

        buttonGroup4.add(fltrStuByName);
        fltrStuByName.setSelected(true);
        fltrStuByName.setText("Name");

        buttonGroup4.add(fltrStuByCode);
        fltrStuByCode.setText("Code");

        buttonGroup4.add(fltrStuByDeg);
        fltrStuByDeg.setText("Degree");

        stuFilterCriteria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                stuFilterCriteriaKeyReleased(evt);
            }
        });

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel3.setText("New Student");

        jLabel27.setText("Name:");

        jLabel29.setText("DOB:");

        jLabel31.setText("Deg.");

        jLabel33.setText("ID Card:");

        saveNewStu.setText("save");
        saveNewStu.setMaximumSize(new java.awt.Dimension(85, 25));
        saveNewStu.setMinimumSize(new java.awt.Dimension(85, 25));
        saveNewStu.setPreferredSize(new java.awt.Dimension(85, 25));
        saveNewStu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveNewStuMouseClicked(evt);
            }
        });

        reloadStuCode.setText("R");
        reloadStuCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reloadStuCodeMouseClicked(evt);
            }
        });

        newStuDob.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        newStuDob.setToolTipText("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel31)
                            .addComponent(jLabel29)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newStuDeg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(newStuName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(newStuIdCard, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reloadStuCode))
                            .addComponent(newStuDob)))
                    .addComponent(saveNewStu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(151, 151, 151))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(newStuName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(newStuDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(newStuDeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(newStuIdCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reloadStuCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveNewStu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel4.setText("Details");

        jLabel22.setText("Code:");

        stuCodeLabl.setText("XXX");

        jLabel25.setText("Name:");

        stuNamelabl.setText("Jhon Doe");

        jLabel28.setText("DOB.:");

        stuDobLabl.setText("2024-01-01");

        jLabel30.setText("Deg.:");

        stuDegLabl.setText("Deg Num");

        jLabel32.setText("Active Loans:");

        activeStuLoans.setText("000");

        jLabel34.setText("All Loans:");

        allStuLoans.setText("000");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stuCodeLabl)
                                    .addComponent(stuNamelabl)
                                    .addComponent(stuDobLabl)
                                    .addComponent(stuDegLabl)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel32))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(activeStuLoans)
                                    .addComponent(allStuLoans))))))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(stuCodeLabl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(stuNamelabl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(stuDobLabl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(stuDegLabl))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(activeStuLoans))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(allStuLoans))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout studentLayout = new javax.swing.GroupLayout(student);
        student.setLayout(studentLayout);
        studentLayout.setHorizontalGroup(
            studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stuContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, studentLayout.createSequentialGroup()
                        .addComponent(fltrStuByName)
                        .addGap(18, 18, 18)
                        .addComponent(fltrStuByCode)
                        .addGap(18, 18, 18)
                        .addComponent(fltrStuByDeg)
                        .addGap(18, 18, 18)
                        .addComponent(stuFilterCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(studentLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(allStudents)
                        .addGap(18, 18, 18)
                        .addComponent(activeStudents)
                        .addGap(18, 18, 18)
                        .addComponent(inactiveStudents))
                    .addGroup(studentLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        studentLayout.setVerticalGroup(
            studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inactiveStudents)
                    .addComponent(activeStudents)
                    .addComponent(allStudents))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fltrStuByName)
                    .addComponent(fltrStuByCode)
                    .addComponent(fltrStuByDeg)
                    .addComponent(stuFilterCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stuContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        container.addTab("Students", student);

        javax.swing.GroupLayout ContaLayout = new javax.swing.GroupLayout(Conta);
        Conta.setLayout(ContaLayout);
        ContaLayout.setHorizontalGroup(
            ContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        ContaLayout.setVerticalGroup(
            ContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
        );

        container.addTab("Admin", Conta);

        getContentPane().add(container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnedBorrowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnedBorrowsActionPerformed
        this.loadBorrows("r");
    }//GEN-LAST:event_returnedBorrowsActionPerformed

    private void returnBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBookBtnActionPerformed
        String code = this.overviewTable.getModel().getValueAt(this.overviewTable.getSelectedRow(), 0).toString();
        if (code != null && !code.isEmpty() && JOptionPane.showConfirmDialog(this, "Sure to cancel this loan?") == 0) {
            Double toPay = this.dataProc.returnABook(code);
            this.load();
            JOptionPane.showMessageDialog(this, "The student will pay: " + String.valueOf(toPay));
        }
    }//GEN-LAST:event_returnBookBtnActionPerformed

    private void reloadBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reloadBtnMouseClicked
        this.load();
        System.out.println("reloaded");
    }//GEN-LAST:event_reloadBtnMouseClicked

    private void activeBorrowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activeBorrowsActionPerformed
        this.loadBorrows("ac");
    }//GEN-LAST:event_activeBorrowsActionPerformed

    private void saveNewBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveNewBorrowActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Sure to save?", "Comfirmation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0) {
            String result = dataProc.saveBorrows(this.stuComboBox.getSelectedIndex(), this.bookComboBox.getSelectedIndex());
            JOptionPane.showMessageDialog(this, result);
            this.load();
        }
    }//GEN-LAST:event_saveNewBorrowActionPerformed

    private void allBorrowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allBorrowsActionPerformed
        this.loadBorrows("all");
    }//GEN-LAST:event_allBorrowsActionPerformed

    private void expiredBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expiredBorrowActionPerformed
        this.loadBorrows("e");
    }//GEN-LAST:event_expiredBorrowActionPerformed

    private void expiringBorrowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expiringBorrowMouseClicked
        this.loadBorrows("et");
    }//GEN-LAST:event_expiringBorrowMouseClicked

    private void overviewTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_overviewTableMouseClicked
        System.out.println(this.overviewTable.getModel().getValueAt(this.overviewTable.getSelectedRow(), 0));
    }//GEN-LAST:event_overviewTableMouseClicked

    private void borrowsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrowsTableMouseClicked
        List<String[]> bDetails = this.dataProc.getBorrowDetails(
                this.borrowsTable.getModel().getValueAt(
                        this.borrowsTable.getSelectedRow(), 0)
                        .toString());
        this.stuCode.setText(bDetails.getFirst()[0]);
        this.stuName.setText(bDetails.getFirst()[1]);
        this.bookCode.setText(bDetails.get(1)[0]);
        this.bookName.setText(bDetails.get(1)[1]);
        this.bookAuthor.setText(bDetails.get(1)[2]);
        this.startBorrowDate.setText(bDetails.get(2)[0]);
        this.endBorrowDate.setText(bDetails.get(2)[1]);
        this.borrowResult.setText(bDetails.get(2)[2] + " days -> Q. " + bDetails.get(2)[3]);
    }//GEN-LAST:event_borrowsTableMouseClicked

    private void findBooksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findBooksBtnActionPerformed
        this.reloadBooksTable();
    }//GEN-LAST:event_findBooksBtnActionPerformed

    private void findCriteriaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_findCriteriaKeyReleased
        this.reloadBooksTable();
    }//GEN-LAST:event_findCriteriaKeyReleased

    private void bookTitleChooserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookTitleChooserMouseClicked
        this.reloadBooksTable();
    }//GEN-LAST:event_bookTitleChooserMouseClicked

    private void bookAuthorChooserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookAuthorChooserMouseClicked
        this.reloadBooksTable();
    }//GEN-LAST:event_bookAuthorChooserMouseClicked

    private void bookEditorialChooserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookEditorialChooserMouseClicked
        this.reloadBooksTable();
    }//GEN-LAST:event_bookEditorialChooserMouseClicked

    private void saveNewBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveNewBookMouseClicked
        //g name, String code, String author, String editorial, String edition, String stock
        String tmp = this.newBookStock.getText().isEmpty() ? "0" : this.newBookStock.getText();
        Book newBook = new Book(
                this.newBookTitle.getText(),
                this.newBookCode.getText(),
                this.newBookAuthor.getText(),
                this.newBookEditorial.getText(),
                this.newBookEdition.getText(),
                tmp
        );
        if (JOptionPane.showConfirmDialog(this, "Sure to save!!") == 0) {
            JOptionPane.showMessageDialog(this, dataProc.saveBook(newBook));
            this.load();
            this.newBookTitle.setText("");
            this.newBookAuthor.setText("");
            this.newBookEditorial.setText("");
            this.newBookEdition.setText("");
            this.newBookCode.setText("");
        }
    }//GEN-LAST:event_saveNewBookMouseClicked

    private void allStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allStudentsMouseClicked
        this.reloadStuTable();
    }//GEN-LAST:event_allStudentsMouseClicked

    private void activeStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_activeStudentsMouseClicked
        this.reloadStuTable();
    }//GEN-LAST:event_activeStudentsMouseClicked

    private void inactiveStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inactiveStudentsMouseClicked
        this.reloadStuTable();
    }//GEN-LAST:event_inactiveStudentsMouseClicked

    private void stuFilterCriteriaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stuFilterCriteriaKeyReleased
        this.reloadStuTable();
    }//GEN-LAST:event_stuFilterCriteriaKeyReleased

    private void stuTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stuTableMouseClicked
        this.loadStuDetails();
    }//GEN-LAST:event_stuTableMouseClicked

    private void saveNewStuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveNewStuMouseClicked
        if (this.newStuIdCard.getText().length() == 8
            && this.newStuName.getText().length() > 3
            && this.newStuDeg.getText().length() > 8
            && this.newStuDob.getText().length() == 10 ) {
            Student newStu = new Student(
                this.newStuIdCard.getText(),
                this.newStuName.getText(),
                this.newStuDeg.getText(),
                this.newStuDob.getText());
            if (JOptionPane.showConfirmDialog(this, "\nSure to save\nthis student?\n") == 0){
                System.out.println(newStu.toString());
                //if result -> reset fields
            }
        } else {
            JOptionPane.showMessageDialog(this, "\nFullfill all the fields to proceed!\n");
        }
        
    }//GEN-LAST:event_saveNewStuMouseClicked

    private void reloadStuCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reloadStuCodeMouseClicked
        this.setNewStuCode();
    }//GEN-LAST:event_reloadStuCodeMouseClicked

    public void load() {
        this.loadOverview();
        this.loadBorrows("a");
        this.loadBooks();
        this.loadStudents("--",'x', 'a');
    }

    private void reloadStuTable() {
        char filtrOn = this.fltrStuByName.isSelected() ? 'n'
                : this.fltrStuByCode.isSelected() ? 'c'
                : this.fltrStuByDeg.isSelected() ? 'd' : '-';
        char filterBy = this.allStudents.isSelected() ? 'a'
                : this.activeStudents.isSelected() ? 'l'
                : this.inactiveStudents.isSelected() ? 'i' : '-';
        this.loadStudents(this.stuFilterCriteria.getText(), filtrOn, filterBy);
        System.out.println("f -> "+filtrOn+filterBy);
    }
    
    private void reloadBooksTable() {
        char filterOn = this.bookTitleChooser.isSelected() ? 't'
                : this.bookAuthorChooser.isSelected() ? 'a'
                : this.bookEditorialChooser.isSelected() ? 'e' : '-';
        this.booksTable.setModel(dataProc.booksTab(this.findCriteria.getText(), filterOn));
        this.booksTable.getColumn("Avaliable").setMaxWidth(60);
        this.booksTable.getColumn("Avaliable").setPreferredWidth(60);
        this.booksTable.getColumn("Stock").setMaxWidth(60);
        this.booksTable.getColumn("Stock").setPreferredWidth(60);
    }

    public void loadOverview() {
        this.overviewTable.setModel(this.dataProc.overviewTab());
        this.overviewTable.getColumn("Code").setPreferredWidth(130);
        this.overviewTable.getColumn("Code").setMaxWidth(130);
        /*this.overviewTable.getColumn("Book ISBN").setPreferredWidth(120);
        this.overviewTable.getColumn("Book ISBN").setMaxWidth(120);*/
        this.overviewTable.getColumn("Fees").setPreferredWidth(65);
        this.overviewTable.getColumn("Fees").setMaxWidth(65);
        /*this.overviewTable.getColumn("Student").setPreferredWidth(90);
        this.overviewTable.getColumn("Student").setMaxWidth(90);*/
        this.overviewTable.getColumn("Days").setPreferredWidth(55);
        this.overviewTable.getColumn("Days").setMaxWidth(55);

        HashMap map = this.dataProc.getStatistics();
        this.brActiveNum.setText(String.valueOf(map.get("borrowedBooks")));
        this.boBorrwdNum.setText(String.valueOf(map.get("borrowedBooks")));
        this.regStudentsNum.setText(String.valueOf(map.get("students")));
        this.brExprNum.setText(String.valueOf(map.get("expiredBorr")));
        this.boAvailNum.setText(String.valueOf((Integer) map.get("totBook") - (Integer) map.get("borrowedBooks")));
    }

    public void loadBorrows(String filter) {
        this.borrowsTable.setModel(this.dataProc.borrowsTab(filter));
        this.borrowsTable.getColumn("Code").setPreferredWidth(130);
        this.borrowsTable.getColumn("Code").setMaxWidth(130);
        this.borrowsTable.getColumn("Days").setPreferredWidth(55);
        this.borrowsTable.getColumn("Days").setMaxWidth(55);
        this.borrowsTable.getColumn("Fees").setPreferredWidth(65);
        this.borrowsTable.getColumn("Fees").setMaxWidth(65);
        this.borrowsTable.getColumn("Start Date").setPreferredWidth(80);
        this.borrowsTable.getColumn("Start Date").setMaxWidth(80);
        this.borrowsTable.getColumn("End Date").setPreferredWidth(80);
        this.borrowsTable.getColumn("End Date").setMaxWidth(80);

        DefaultComboBoxModel[] newBorrowModels = this.dataProc.newBorrowConf();
        this.bookComboBox.setModel(newBorrowModels[0]);
        this.stuComboBox.setModel(newBorrowModels[1]);

        this.dailyCost.setText(String.valueOf(this.dailyFee));
        this.duration.setText(String.valueOf(this.daysPerBorrow));

    }

    public void loadBooks() {
        this.booksTable.setModel(this.dataProc.booksTab("something", '-'));
        this.booksTable.getColumn("Avaliable").setMaxWidth(60);
        this.booksTable.getColumn("Avaliable").setPreferredWidth(60);
        this.booksTable.getColumn("Stock").setMaxWidth(60);
        this.booksTable.getColumn("Stock").setPreferredWidth(60);
        
        HashMap map = this.dataProc.getStatistics();
        this.totalReg.setText(map.get("totBook").toString());
        this.currOutOf.setText(map.get("borrowedBooks").toString());
    }
    
    public void loadStudents(String filter, char on, char by){
        this.stuTable.setModel(this.dataProc.studentsTab(filter, on, by));
        this.stuTable.getColumn("Code").setMaxWidth(70);
        this.stuTable.getColumn("Code").setPreferredWidth(70);
        
        setNewStuCode();
    }
    
    private void loadStuDetails(){
        Student detailedStu = dataProc.getDetailedStudent(this.stuTable.getValueAt(this.stuTable.getSelectedRow(), 0).toString());
        this.stuCodeLabl.setText(detailedStu.getID());
        this.stuNamelabl.setText(detailedStu.getName());
        this.stuDobLabl.setText(detailedStu.getDob().toString());
        this.stuDegLabl.setText(detailedStu.getDegree());
        this.activeStuLoans.setText(Integer.toString(detailedStu.getActiveLoans()));
        this.allStuLoans.setText(Integer.toString(detailedStu.getAllLoans()));
    }
  
    private void setNewStuCode() {
        Random rnd = new Random();
        String seed = "BCDEFGHIJKLMNOPQRSTUVWXYZ1234567890", newCode = "24";
        for (int i = 0; i < 6; i++) {
            newCode += seed.charAt(rnd.nextInt(seed.length()));
        }
        this.newStuIdCard.setText(newCode);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Conta;
    private javax.swing.JRadioButton activeBorrows;
    private javax.swing.JLabel activeStuLoans;
    private javax.swing.JRadioButton activeStudents;
    private javax.swing.JRadioButton allBorrows;
    private javax.swing.JLabel allStuLoans;
    private javax.swing.JRadioButton allStudents;
    private javax.swing.JLabel boAvail;
    private javax.swing.JLabel boAvailNum;
    private javax.swing.JLabel boBorrwd;
    private javax.swing.JLabel boBorrwdNum;
    private javax.swing.JPanel book;
    private javax.swing.JLabel bookAuthor;
    private javax.swing.JRadioButton bookAuthorChooser;
    private javax.swing.JLabel bookCode;
    private javax.swing.JComboBox<String> bookComboBox;
    private javax.swing.JScrollPane bookContainer;
    private javax.swing.JRadioButton bookEditorialChooser;
    private javax.swing.JLabel bookName;
    private javax.swing.JLabel bookOverview;
    private javax.swing.JRadioButton bookTitleChooser;
    private javax.swing.JTable booksTable;
    private javax.swing.JPanel borrow;
    private javax.swing.JLabel borrowResult;
    private javax.swing.JTable borrowsTable;
    private javax.swing.JLabel brActive;
    private javax.swing.JLabel brActiveNum;
    private javax.swing.JLabel brExpr;
    private javax.swing.JLabel brExprNum;
    private javax.swing.JLabel brOverview;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JTabbedPane container;
    private javax.swing.JLabel currOutOf;
    private javax.swing.JLabel dailyCost;
    private javax.swing.JPanel detailsPanel;
    private javax.swing.JLabel duration;
    private javax.swing.JLabel endBorrowDate;
    private javax.swing.JRadioButton expiredBorrow;
    private javax.swing.JRadioButton expiringBorrow;
    private javax.swing.JButton findBooksBtn;
    private javax.swing.JTextField findCriteria;
    private javax.swing.JRadioButton fltrStuByCode;
    private javax.swing.JRadioButton fltrStuByDeg;
    private javax.swing.JRadioButton fltrStuByName;
    private javax.swing.JRadioButton inactiveStudents;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField newBookAuthor;
    private javax.swing.JTextField newBookCode;
    private javax.swing.JTextField newBookEdition;
    private javax.swing.JTextField newBookEditorial;
    private javax.swing.JTextField newBookStock;
    private javax.swing.JTextField newBookTitle;
    private javax.swing.JTextField newStuDeg;
    private javax.swing.JFormattedTextField newStuDob;
    private javax.swing.JTextField newStuIdCard;
    private javax.swing.JTextField newStuName;
    private javax.swing.JPanel overview;
    private javax.swing.JScrollPane overviewContainer;
    private javax.swing.JScrollPane overviewContainer1;
    private javax.swing.JTable overviewTable;
    private javax.swing.JLabel regStudentsNum;
    private javax.swing.JButton reloadBtn;
    private javax.swing.JButton reloadStuCode;
    private javax.swing.JButton returnBookBtn;
    private javax.swing.JRadioButton returnedBorrows;
    private javax.swing.JLabel sOverview;
    private javax.swing.JButton saveNewBook;
    private javax.swing.JButton saveNewBorrow;
    private javax.swing.JButton saveNewStu;
    private javax.swing.JLabel startBorrowDate;
    private javax.swing.JLabel stuCode;
    private javax.swing.JLabel stuCodeLabl;
    private javax.swing.JComboBox<String> stuComboBox;
    private javax.swing.JScrollPane stuContainer;
    private javax.swing.JLabel stuDegLabl;
    private javax.swing.JLabel stuDobLabl;
    private javax.swing.JTextField stuFilterCriteria;
    private javax.swing.JLabel stuName;
    private javax.swing.JLabel stuNamelabl;
    private javax.swing.JTable stuTable;
    private javax.swing.JPanel student;
    private javax.swing.JLabel title;
    private javax.swing.JLabel totalReg;
    // End of variables declaration//GEN-END:variables
}
